package nl.suitless.assistantservice.Data.repositories;

import nl.suitless.assistantservice.Domain.Entities.Module;
import org.springframework.data.mongodb.repository.MongoRepository;

import java.util.Optional;

/**
 * Repository generated by the Module Service. This service only uses it for obtaining modules
 * @author Martijn Dormans
 * @version 1.0
 * @since 5-6-2019
 */
public interface IModuleRepository extends MongoRepository<Module, Integer> {
    Optional<Module> findByName(String name);
}
